### ISSUE TITLE
Pre-commit hooks for formatting, lint in CI

### ISSUE THREAD

**Issue by ellenhp** [headwaymaps/headway#126]

**Comment by mcapodici** [comment]
Do you mean precommit that runs on local machine? Or only in CI? I think you now check for formatting in CI from what I have seen. Having it run local would probably save some hassles.

**Comment by ellenhp** [comment]
Yeah, the CI portion of this issue is complete, but I do want to add local pre-commit hooks. I don't have a ton of experience with them but I think they need to be installed manually, so they're optional.
