### ISSUE TITLE
error when trying to start Headway locally

### ISSUE THREAD

**Issue by eyarz** [headwaymaps/headway#131]
I followed the steps in the "[Run it yourself](https://about.maps.earth/)" to start my own server.
I installed `earthly` and made sure my [system requirements](https://github.com/headwaymaps/headway#system-requirements) are set correctly, but I'm getting the following error (when running `$ earthly -P +build --area=Amsterdam`):

```
+planetiler-build-mbtiles *failed* | Command /bin/sh -c 'sha256sum /planetiler/planetiler.jar && java -jar /planetiler/planetiler.jar --force osm_path=/data/data.osm.pbf' failed with exit code 1
+planetiler-build-mbtiles *failed* | +planetiler-build-mbtiles *failed* | ERROR: Command exited with non-zero code: RUN sha256sum /planetiler/planetiler.jar && java -jar /planetiler/planetiler.jar --force osm_path=/data/data.osm.pbf
Share your logs with an Earthly account (experimental)! Register for one at https://ci.earthly.dev.
Error: build target: build main: failed to solve: process "/bin/sh -c EARTHLY_LOCALLY=false PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin TZ=America/New_York area=Amsterdam /usr/bin/earth_debugger /bin/sh -c 'sha256sum /planetiler/planetiler.jar && java -jar /planetiler/planetiler.jar --force osm_path=/data/data.osm.pbf'" did not complete successfully: exit code: 1
```

Any clues on what can cause this error?

**Comment by ellenhp** [comment]
Off the top of my head that could be either the planetiler.jar file not matching the correct hash, or it could be a failure during tile generation. Were there any logs above this that could provide more information? I'm going to try and reproduce the error locally too.

**Comment by ellenhp** [comment]
I was unable to reproduce this error, but it could be a problem with the download of planetiler.jar. As a debugging step, you could run `earthly prune` which will clear the Earthly cache and force it to re-download everything.

**Comment by eyarz** [comment]
Increasing the machine resources solved it.
thanks!

**Comment by eyarz** [comment]
Increasing the machine resources solved it.
thanks!
