### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ellenhp** [headwaymaps/headway#141]
Right now the readme is a bit unclear about system requirements (I'm bad at technical writing) and the meaning of "over 200 different cities are currently supported" is also unclear in the context of custom extracts and planet-scale installations being supported.

**Comment by kresp0** [comment]
https://github.com/headwaymaps/headway/pull/143

**Comment by ellenhp** [comment]
All that remains is moving the paragraph about full-planet considerations to its own file and maybe having the BUILD file reference it. I'll get to that soon, but I'm trying to take the day off today :)
