### ISSUE TITLE
waste_basket shown on medium zoom levels

### ISSUE THREAD

**Issue by kresp0** [headwaymaps/headway#144]
Currently, `waste_basket` features are shown at medium zoom levels. I think it would be better if those are shown only on zoom ≥ 19, like the [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto) does.

The image attached is a bit of an exaggeration, as for my custom extract I'm adding `waste_basket` and many other Open Data elements on top of the OSM streets and parks.

![waste basket](https://user-images.githubusercontent.com/420430/189482552-cfeecc6d-d4e4-4869-91c9-f519eb915a59.png)

**Comment by ellenhp** [comment]
I noticed this too on your instance. I'm not sure if 19 is the correct zoom for this, but I agree we should make it a deeper zoom than what it currently is. I've already made the change to OSM Liberty to remove 3d buildings, so we can continue editing our fork to fix this.

**Comment by michaelkirk** [comment]
I'm not sure when exactly this was fixed, but I can't reproduce it. Let me know if I'm mistaken.
