### ISSUE TITLE
Autocomplete suggestions for "large scale" objects (e.g. city or state) 

### ISSUE THREAD

**Issue by michaelkirk** [headwaymaps/headway#153]
Often I'm using maps for routing, but sometimes I'm just using it as a map, like I just want to see where something is.

The autocomplete seems to work well for street addresses and place names e.g. "123 Jackson Seattle" or "Gasworks Park Seattle" but if I'm just searching for "Seattle" or "Oregon" none of the results are what I'd expect.

<img width="500" alt="Screen Shot 2022-09-15 at 12 36 46 PM" src="https://user-images.githubusercontent.com/217057/190483758-90ba7947-e727-40e0-a185-12dcc55a6db2.png">

Compare to:

**Goog**
<img width="399" alt="Screen Shot 2022-09-15 at 12 32 38 PM" src="https://user-images.githubusercontent.com/217057/190483898-49da07bd-5e7b-4a92-961c-d68cbff8a701.png">

**Bing**
<img width="624" alt="Screen Shot 2022-09-15 at 12 33 11 PM" src="https://user-images.githubusercontent.com/217057/190483899-346d23df-559f-4a73-a626-258aa2349b75.png">

**Apple**
<img width="299" alt="Screen Shot 2022-09-15 at 12 33 37 PM" src="https://user-images.githubusercontent.com/217057/190483901-72affb7b-8ca7-4e3e-bcca-0f6f6bd5ab15.png">

I'm assuming this is an issue with Pelias - either with the software ourselves or our configuration of it.

**Comment by ellenhp** [comment]
I've noticed this too. It's gotta be an issue with the way we're configuring Pelias because it works fine on geocode.earth. I can think of two things:

1. I built the index on maps.earth using Daylight Maps, which by default excludes admin areas. Pelias has access to Who's On First data but perhaps it's not using those without a matching admin area in OSM?
2. It could just be some misconfiguration in pelias.json.template

It would be easy to rule out (1) by building a pelias index from a small OSM extract that does include admin areas and checking whether pelias works properly when brought up with that index.

**Comment by michaelkirk** [comment]
I'm planning to look at this next unless I hear otherwise.

**Comment by ellenhp** [comment]
Sounds good. If this issue does not repro for other OSM extracts then it's probably just an issue with maps.earth. I'm in the process of migrating from OVH to hetzner so I can probably just do an index rebuild during the process to fix that. But if it does repro with other OSM extracts then we'll need to figure out a config fix.

**Comment by michaelkirk** [comment]
Notes for myself mostly...

>  it works fine on geocode.earth

Indeed, hitting `geocode.earth` with: `text=Denv&size=5&layers=locality` gives good results.

I noticed that the first result from geocode.earth (the ones we want) are from the WOF dataset:

<details>
<summary> response from geocode.earth</summary>
<pre>
{                                                                                                                                       
  "geocoding": {                                                                                                                        
    "version": "0.2",                                                                                                                   
    "attribution": "https://geocode.earth/guidelines",                                                                                  
    "query": {                                                                                                                          
      "text": "Denv",                                                                                                                   
      "parser": "pelias",                                                                                                               
      "parsed_text": {                                                                                                                  
        "subject": "Denv"                                                                                                               
      },                                                                                                                                
      "size": 5,                                                                                                                        
      "layers": [                                                                                                                       
        "locality"                                                                                                                      
      ],                                                                                                                                
      "private": false,                                                                                                                 
      "lang": {                                                                                                                         
        "name": "English",                                                                                                              
        "iso6391": "en",                                                                                                                
        "iso6393": "eng",                                                                                                               
        "via": "header",                                                                                                                
        "defaulted": false                                                                                                              
      },                                                                                                                                
      "querySize": 20                                                                                                                   
    },                                                              
    "engine": {                                                     
      "name": "Pelias",                                             
      "author": "Mapzen",                                           
      "version": "1.0"                                              
    },                                                              
    "timestamp": 1663278656733                                      
  },                                                                
  "type": "FeatureCollection",                                                                                                          
  "features": [                                                                                                                         
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -104.985798,
          39.740959
        ]
      },
      "properties": {
        "id": "85928879",
        "gid": "whosonfirst:locality:85928879",
        "layer": "locality",
        "source": "whosonfirst",
        "source_id": "85928879",
        "country_code": "US",
        "name": "Denver",
        "accuracy": "centroid",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Colorado",
        "region_gid": "whosonfirst:region:85688603",
        "region_a": "CO",
        "county": "Denver County",
       ...
       TRUNCATED
       ...
</pre>
</details>


Trying to similarly specifying the `locality` layer against maps.earth gives *no* results:
<details>
<summary>Response from maps.earth</summary>
<pre>
{
  "geocoding": {
    "version": "0.2",
    "attribution": "http://peliasapi:4000/attribution",
    "query": {
      "text": "Denver",
      "parser": "pelias",
      "parsed_text": {
        "subject": "Denver",
        "locality": "Denver"
      },
      "size": 10,
      "layers": [
        "locality"
      ],
      "private": false,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "via": "default",
        "defaulted": true
      },
      "querySize": 20
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1663278335785
  },
  "type": "FeatureCollection",
  "features": []
}
</pre>
</div>
</details>

I get a similar result when running against my *own* build which appears to be using an extract from https://download.bbbike.org.

> It would be easy to rule out (1) by building a pelias index from a small OSM extract that does include admin areas and checking whether pelias works properly when brought up with that index.

To do this, I snagged all of washington state from https://download.geofabrik.de/north-america/us/washington.html and moved it to `<repo-root>/Seattle.osm.pbf`, then restarted (first doing `docker-compose down --volume` as instructed in BUILD.md). I'm not very familiar with this process yet - does that seem reasonable?

Here's a maybe interesting snippet from that build process:
<img width="1243" alt="Screen Shot 2022-09-15 at 5 40 50 PM" src="https://user-images.githubusercontent.com/217057/190528517-a670b63b-b7ec-4130-9ea1-9da8133f6b14.png">

> `locality worker loaded 48113 features in 20.478 seconds` 👀 

After doing this and rebuilding, I still see only see results from the "openstreetmap" source, and the top level Seattle locality is not one of them.

<img width="944" alt="Screen Shot 2022-09-15 at 5 50 12 PM" src="https://user-images.githubusercontent.com/217057/190527921-8a7caba9-4fb4-4d3d-86cb-b80d9a9ec190.png">

I'm going to have to pause this work for today, but can come back to it on Monday if it's still outstanding.

**Comment by ellenhp** [comment]
> To do this, I snagged all of washington state from https://download.geofabrik.de/north-america/us/washington.html and moved it to `<repo-root>/Seattle.osm.pbf`, then restarted (first doing `docker-compose down --volume` as instructed in BUILD.md). I'm not very familiar with this process yet - does that seem reasonable?

Just want to mention that the earthly build config is perfectly happy to accept arbitrary extracts without you having to change their name first.

> After doing this and rebuilding, I still see only see results from the "openstreetmap" source, and the top level Seattle locality is not one of them.

This ultimately tipped me off that something was amiss with the way the WOF data was being treated. It turns out that we weren't loading any of the WOF data into elasticsearch. I had mistakenly assumed that loading it into the `pelias/placeholder` index would be enough but it appears that the placeholder index isn't used for autocomplete queries. It must not support prefix searches I'd guess.

I have a fix, currently minimizing the diff. PR soon. :)

**Comment by michaelkirk** [comment]
I just wanted to confirm that this fixed things for me - I'm seeing locality results in the autocomplete results.

And, as expected, the result is from `source: whosonfirst`. 👍 

<img width="512" alt="Screen Shot 2022-09-17 at 9 21 08 AM" src="https://user-images.githubusercontent.com/217057/190864245-e984baf9-754a-4f93-befd-adf715f8254f.png">

Thank you!
