### ISSUE TITLE
The map should start more zoomed in when possible

### ISSUE THREAD

**Issue by michaelkirk** [headwaymaps/headway#167]
There's a little nuance to how/if we might solve this, but the problem is basically: 

> It's annoying to start with the map zoomed all the way out. 

For one, it takes longer to zoom in to where you're interested and (more importantly?) geocoding results will work much better with the contextual hint of where the map is centered.

I don't know the best way to address this, but a couple proposals:

For first time visitors we **could** do something with location inference, but that seems like higher hanging potentially fraught fruit.

So for starts, I wanted to focus on return visitors:

Some of them will have shared their location with us, so we could center on their actual location, but it actually takes a little while to get their location from the browser, and it's a little disorienting to just start automatically zooming the map just after loading. And obviously this won't work at all for people who haven't shared their location.

Maybe a better approach then,  we could have the client remember the last place the map was centered. Upon returning to the site, rather than showing the whole planet, we could center the map here at a zoom level of 10 or so.

**Comment by ellenhp** [comment]
> Maybe a better approach then, we could have the client remember the last place the map was centered. Upon returning to the site, rather than showing the whole planet, we could center the map here at a zoom level of 10 or so.

I like this approach. It would do a lot to make the app feel more usable to be able to open it and get viewport biasing right away.
