### ISSUE TITLE
"Show my location" feature

### ISSUE THREAD

**Issue by maciejla** [headwaymaps/headway#180]
It would be nice to have a feature that shows you where you are, just like on the osm.org website 
![image](https://user-images.githubusercontent.com/85807099/195156174-ed0fd65f-255c-446c-bea7-a3c7a8bdc937.png)

**Comment by michaelkirk** [comment]
![image](https://user-images.githubusercontent.com/217057/195170054-80090430-a584-4c8b-af45-005ddbed08c4.jpeg)

Does this existing button work for you? 

Note that there is a fix related to safari 15 users which has been merged but not yet deployed.

**Comment by michaelkirk** [comment]
Maybe we should consider switching icons. The "compass arrow" icon seems to be more common than the "target" icon we're currently using.

**Comment by maciejla** [comment]
This icon is good, I just haven't noticed it :) probably because of it's color when not available :) sorry for bothering you
