### ISSUE TITLE
Question - How to pass multiple OTP-Instances to Transitmux using Earthfile

### ISSUE THREAD

**Issue by CKranebitter** [headwaymaps/headway#229]
Great work the last few days.
I've seen that it may be possible using multiple OTP-Instances.
I build my OTP-Instances outside headway.
Can I modify the transitmux-logic in the Earthfile to pass these prebuilt instances like this: 
`CMD ["http://opentripplanner_berlin:8080/otp/routers","http://opentripplanner_vienna:8080/otp/routers"]
`
Thanks for your enormous work on this.
Best.

**Comment by michaelkirk** [comment]
Hello!

I haven't tested transitmux with containers other than what is built by the Earthfile, but if you have an OTP instance at a different URL, it should work without having to rebuild any containers. You'll only need to override the container's arguments.

With docker/compose this is via the `CMD` parameter, or if you're using kubernetes, the same thing is (more reasonably) called `args`.

https://docs.docker.com/engine/reference/run/#overriding-dockerfile-image-defaults

**Comment by CKranebitter** [comment]
I get that.
But I was asking what's the correct way to pass multiple instances to the transitmux-container.
Is this supposed to work?

`CMD ["http://opentripplanner_berlin:8080/otp/routers","http://opentripplanner_vienna:8080/otp/routers"] `

**Comment by michaelkirk** [comment]
That looks about rights Have you tried it? What happened? On Jan 21, 2023, at 08:55, CKranebitter ***@***.***> wrote:﻿
I get that.
But I was asking what's the correct way to pass multiple instances to the transitmux-container.
Is this supposed to work?
CMD ["http://opentripplanner_berlin:8080/otp/routers","http://opentripplanner_vienna:8080/otp/routers"]

**Comment by CKranebitter** [comment]
No luck. I cant get it to work.
I wonder why my OTP-Service is reachable with `http://opentripplanner:8000` when I explicitly name the container `opentripplanner_berlin`

**Comment by michaelkirk** [comment]
Are you running in kubernetes or docker compose?

Can you share any of the corresponding configuration? 
Can you share any specific error output that you're seeing?

**Comment by CKranebitter** [comment]
Managed to get it to work after I put OTP behind a reverse proxy.
Running docker swarm.

A direct call via `http://opentripplanner_berlin:8080` did not work.
It seems that there is another layer where the Transitmux-Container can reach the OTP-instance generated by the Earthfile via `http://opentripplanner:8000` although this Container is named `opentripplanner_berlin`.
I just dont get where this happens.
But your code is working. It's just an understanding issue of mine.
Thanks for your work and help.
I much appreciate it.
