### ISSUE TITLE
Headway shows trip-items as "Walk" instead of "Subway"

### ISSUE THREAD

**Issue by spammads** [headwaymaps/headway#237]
Hi there.
I experience a strange behavior.
Headway shows transit-items in the left overview as "walking"-items whereas the api-endpoint `otp/plan` returns subway-items.
I made you a pastebin which burns after read.
[Prettyfied-Json-Response of the Otp-instance](https://pastebin.com/p7jWpMJN)

<img width="123" alt="Screenshot 2023-01-28 at 12 28 40" src="https://user-images.githubusercontent.com/63287042/215264081-0f4b7ef4-10fd-4018-b52f-b0d0654f242b.png">

**Comment by michaelkirk** [comment]
Hi! Thanks for reporting. This should be fixed as of #238.

Let me know if you continue to have problems.

**Comment by spammads** [comment]
Hi! Thanks for resolving. I tested it and it works.
Just one more suggestion: It would be great if headway would respect the `routeColor` of the OTP-Json to color the suggested subway-line in the tiles instead of just using red as the color. People are heavily attached to subway-colors. At least where I live :)
