### ISSUE TITLE
about.maps.earth certificate error

### ISSUE THREAD

**Issue by frewsxcv** [headwaymaps/headway#249]
https://about.maps.earth/
<img width="998" alt="Screenshot 2023-02-19 at 11 38 56 PM" src="https://user-images.githubusercontent.com/416575/220010835-53d60b12-7f29-4f05-92d1-2de43b6113f9.png">

**Comment by michaelkirk** [comment]
Hi! Thanks for noticing. The ssl certificate expired about two hours prior.

It was all managed by GH (which IIRC is ultimately using let's encrypt), so I'm not sure what happened. 

Anyway, I juggled some things around and it seems to be back up.
