### ISSUE TITLE
Is there more documentatin besides BUILD.md

### ISSUE THREAD

**Issue by borys-spiridonov-yal** [headwaymaps/headway#282]
Hi,
I'm looking into this project and was wondering if there is any documentation besides BUILD.md
The readme.md is extremely short and does not explain anything about the project's architecture or how to run it.
I'm sorry if I missed something

**Comment by michaelkirk** [comment]
I agree the project is pretty sparse on architectural documentation. There's also https://about.maps.earth, but there's admittedly not much there.

BUILD.md is intended to be sufficient to get you up and running, but I'm sure it could be improved. 

Did you encounter a specific problem? If so can you elaborate on what you tried and what happened?

**Comment by ellenhp** [comment]
Yeah it's definitely a bit sparse especially compared to what's available for its core services. I wrote some documentation in at the beginning last summer and it's been improved then but I don't the scope has been changed. It might be nice to have a user guide, but it's not clear how many users we have other than the main maps.earth instance.

**Comment by borys-spiridonov-yal** [comment]
Thanks for your prompt responses. I'm considering using hedwaymeps to host our own maps server instance (mainly to use the API for tiles server and routing). And I was unable to find any information on what is running under the hood of hedwaymeps.
1. Is it the standard OSM suite apps like Overpass and Nominatim or is it something different?
2. Does it expose Overpoass API?
3. What database is in use and can I host the database outside the main app container?

**Comment by michaelkirk** [comment]
Headway is:
1. a bunch of other projects stitched together
2. a consolidated build system for those projects
3. a web frontend

The various components:
- web frontend
  - custom quasar/vue.js app in [services/frontend](https://github.com/headwaymaps/headway/tree/main/services/frontend)
- build system
  -  Earthly [read more](https://github.com/headwaymaps/headway/blob/main/BUILD.md)
- map tiles
  - tile building: [planetiler](https://github.com/onthegomap/planetiler)
  - tile server: https://www.npmjs.com/package/tileserver-gl-light
- geocoding: 
  - [pelias](https://pelias.io/)
- routing
  - bike, pedestrian, cars: [valhalla](https://github.com/valhalla/valhalla)
  - transit: [OpenTripPlanner](http://www.opentripplanner.org/)

> Is it the standard OSM suite apps like Overpass and Nominatim or is it something different?

See above - we don't use overpass or nominatim, but we do use a bunch of other existing software packages.

> Does it expose Overpoass API?

n/a - see above

> What database is in use and can I host the database outside the main app container?

Our various services are powered a variety of static file formats optimized for their different purposes — there is no singular database, e.g. postgres. The files we use are generated in a batch fashion from inputs like an osm.pbf exports, WOF extracts, and GTFS feeds using the earthly build system.

**Comment by borys-spiridonov-yal** [comment]
Thank you, this is super helpful!
