### ISSUE TITLE
Error when building with north-america-latest

### ISSUE THREAD

**Issue by mmccann13** [headwaymaps/headway#291]
I'm attempting to build using a custom osm from https://[download.geofabrik.de](https://download.geofabrik.de/north-america.html)/north-america.html

I've copied the .pbf file into the root directory of the repo.  When I execute the command

`earthly -P +build --area="north-america-latest" --countries="ALL"`

I receive the error:

```
            _unknown *failed* | build target: build main: failed to solve: async earthfile2llb for +save: Earthfile line 30:4 apply FROM +save-base: apply build +save-base: earthfile2llb for +save-base: Earthfile line 833:4 apply FROM debian:bullseye-slim: resolve image config for debian:bullseye-slim: failed to do request: Head "https://registry-1.docker.io/v2/library/debian/manifests/bullseye-slim": dial tcp [2600:1f18:2148:bc02:cfd8:db68:ea1f:277c]:443: connect: cannot assign requested address
            _unknown *failed* | in              github.com/headwaymaps/headway:main+save-base
            _unknown *failed* | in              github.com/headwaymaps/headway:main+save
```

The earthly log url is: https://cloud.earthly.dev/builds/63fe5448-c86f-4346-843a-7cde6b1b6277

The environment I'm building is a clean Windows 11 install with Docker Desktop and WSL2/Ubuntu.  Latest versions of everything as of 10/13/2023.

**Comment by ellenhp** [comment]
This seems like it may be a docker networking issue.

> connect: cannot assign requested address

Might be something worth googling. Without knowing more about your networking setup I can't say for sure what's causing this.

**Comment by michaelkirk** [comment]
Closing this due to lack of response.
