### ISSUE TITLE
README seems incomplete or maybe it's a me issue?

### ISSUE THREAD

**Issue by danv8086** [headwaymaps/headway#297]
I've installed Git, Docker + earthly. Hello World via Earthly installed okay, however if I run "earthly -P +build --area=Amsterdam" I get 

` Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)

 Build 🔧
————————————————————————————————————————————————————————————————————————————————

Error: resolve build context for target +build: No Earthfile nor build.earth file found for target +build
🛰️ Reuse cache between CI runs with Earthly Satellites! 2-20X faster than without cache. Generous free tier https://cloud.earthly.dev
`

My goal is to use the pbf for the world but reading this - "Copy your OSM extract into Headway's top-level directory (same directory as this file)", it doesn't make sense where the OSM extract needs to go? If I haven't run earthly -P +build yet the directory can't exist can it? Any ideas appreciated!

**Comment by ellenhp** [comment]
What's your working directory when you run that command? It should be the top-level headway directory. You should be able to `ls Earthfile` before that command without any "no file found" errors.

**Comment by michaelkirk** [comment]
Closing this due to lack of response.
