### ISSUE TITLE
Add a way to disable transit

### ISSUE THREAD

**Issue by ellenhp** [headwaymaps/headway#32]
OTP right now is the biggest memory hog by far, so it would be nice to let people disable it if they don't have memory to spare.

**Comment by bwoodcock** [comment]
This is a really naive question, for which I apologize, but would it be feasible to have this be a run-time loadable module?  Such that if a person didn't often use transit, but did once in a while, the transit module could be loaded (at, presumably, considerable one-time expense), and then flushed after some period (a couple of hours?) of inactivity, or when more pressing needs for that memory arose?  From a social-responsibility perspective, having instances which are never able to supply transit directions, and thus make transit directions unpredictably available, would be a disincentive to transit use, which would be a bad thing.

**Comment by ellenhp** [comment]
Not naive! The issue with that is building the OpenTripPlanner index requires a one-time cost in latency that's completely unacceptable for an end-user, and moveover the machine running the stack might not be able to spare the RAM to build the graph or run OTP.
