### ISSUE TITLE
Add support to arbitrary OSM extracts

### ISSUE THREAD

**Issue by kodxana** [headwaymaps/headway#46]

**Comment by ellenhp** [comment]
If this seems reasonable to people I'll probably try an iron out the issues later today or maybe sometime this week if I don't get to it today. I think there will be issues.

**Comment by ElRoberto538** [comment]
Hi @ellenhp, have you started on this? I want to add my entire region of my country as nothing near me is available on BBBike. Your method for updating the Makefile is easy enough for me to do.

e.g. `make custom NewZealandNorthIsland "-122.462 47.394 -122.005 47.831"`

**Comment by ellenhp** [comment]
I haven't started on this yet, and I'm on a small vacation right now so I won't be able to until I get back. I'm glad people are interested though! If you want to try feel free to comment here with any issues you find and any workarounds. Off the top of my head I know you'll need to define the bbox and the name like you did in your example command.

**Comment by ellenhp** [comment]
This should be implemented now. See https://github.com/headwaymaps/headway/blob/main/BUILD.md for documentation and please do open issues if you find any!
