### ISSUE TITLE
Project website

### ISSUE THREAD

**Issue by ellenhp** [headwaymaps/headway#49]
I want to make a website for the project that captures the convenience of all those sites out there that tell you to pipe curl into bash to install their software. I own the domain [maps.earth](https://maps.earth/) and want to use it for this site.

What I'm imagining is a world map rendered with pmtiles, and a UI on top of it that lets you search for an administrative area that may not be in the BBBike extract list, e.g. Atlanta, Georgia. The UI will let people draw a bounding box over an area they care about and prepare an OSM extract for them. (tbd how to make this scale, but I have some ideas). It would also collect GTFS feeds for the bounding box, and maybe even let people disable some of them. Once everything is selected, a make command could be generated with a token for that user's selections.

Running the command would kick off the OSM extract and spin wait on the user's machine while it's running, then download the extract and GTFS feeds and kick off the rest of the build per normal.

This is a long-term suggestion but I've looked at the logs for the demo server and almost all of the geocoder requests are for cities outside of the Seattle metro area. It turns out people really just want to see their own cities on the map before they get really interested.

**Comment by ellenhp** [comment]
Closing because I want to put a full-planet installation on maps.earth instead.

**Comment by 3nprob** [comment]
It could still be nice with a static product page with links to docs/about etc. Could be super simple. If nothing else it'd provide an entrypoint in case of operational issues or other downtime of the actual instance.
