### ISSUE TITLE
[Bug] Error when hosting behind https reverse proxy

### ISSUE THREAD

**Issue by RaphMad** [headwaymaps/headway#59]
When hosting behind a reverse proxy using https, tiles cannot be loaded.

![image](https://user-images.githubusercontent.com/5588470/172661664-45aced33-5332-4d0d-86ca-96b1d799d356.png)

I was able to track it down to the `magic_string_magic` dummy host that is defined in https://github.com/headwaymaps/headway/blob/main/web/nginx.conf.template#L53.

It seems to only redirect accesses to `http://magic_string_magic`, but when the whole page is `https`, also this call will be `https://magic_string_magic`.

I was able to fix it by manually changing both occurrences of  `http://magic_string_magic` to  `https://magic_string_magic` (but of course this only works temporary until the container gets re-created).

I think a proper fix would be to have an ENV var defining whether the whole stack is hosted behind https and changing the entries in `nginx.conf.template` accordingly (could maybe even be dynamically parsed from HEADWAY_PUBLIC_URL).

**Comment by ellenhp** [comment]
Hey! Thanks for trying this out! My demo server is currently behind an nginx reverse proxy with HTTPS. https://maps.ellenhp.me/

> It seems to only redirect accesses to http://magic_string_magic, but when the whole page is https, also this call will be https://magic_string_magic.

This isn't quite true because of the way the map styles work. Is your (outer) nginx proxy terminated TLS and then making *another* HTTPS request out to headway, by any chance?

**Comment by RaphMad** [comment]
Latest main (https://github.com/headwaymaps/headway/commit/6ca45b379ae40ef2cb28e87ec7998263dca90e9c as of now).

Also using `[Chromium: 102.0.5005.61 (Official Build) (64-bit)](https://brave.com/latest/)` if that may be an influence, since the request to `https://magic_string_magic` is seen in the dev tools and originates from the browser.

**Comment by ellenhp** [comment]
This should be fixed by #61. Closing for now but I would eventually like to replace the dummy host with something a bit less janky.
