### ISSUE TITLE
Consider replacing GNU Make with Gradle (or something else?)

### ISSUE THREAD

**Issue by ellenhp** [headwaymaps/headway#62]
I went to ToorCamp 2022 recently and had a conversation with someone who suggested I use Gradle for the build system of Headway instead of Make. They mentioned a few benefits, including the fact that if a build step fails then the artifacts from that build step aren't cached or written to disk. It would also cache build artifacts in a smarter way, meaning things don't get evicted from the cache needlessly.

In other words if I ran:

```
make Adelaide
make Seattle
make Adelaide
```

In step 3, Gradle would use the cached Adelaide artifacts from step 1.

Both of these seem huge to me, because they would completely negate the benefits of using `docker build` instead of `docker run`, reduce docker image clutter, and reduce wasted effort spent on updating Makefile style to work on various platforms/versions.

If nobody objects to the use of Gradle in the near future, I think I'll begin work on this. I'm entirely open to using just about anything that provides the cache and reproducibility-on-error benefits that Gradle seems to, just want to evaluate everything on its merits. :)

**Comment by ellenhp** [comment]
Not sure if you have pings set up, or are still following development here but I'm curious what you think @3nprob. I know we discussed how goofy it is to use `docker build` for data processing and I think this would give all of the benefits of that without any of the goofiness. A few people I've talked to have objected to the idea of using a heavyweight build system for this so I'm curious if you have any insight. The input you've provided so far has been really valuable.

**Comment by 3nprob** [comment]
Some observations:

The headway build process (all managed through `make` configured by the Makefile) currently concerns itself with building code (compilation), images (packaging) and data (data processing).

Compilation is the primary use-case for `make`. Processing data through make and other code-build-tools is not necessarily super uncommon or a bad idea per se but clunky ergonomics are not a big surprise. Similarly with `docker build`.

So I think the three main directions here I see would be

1. Keep current general Makefile+docker build combo but try to improve on it
2. Separate the concerns and move the data processing part out of the build system to something different (probably something more made for the purpose)
3. Replace the build system with something different

So 3 would be what's proposed in this issue (Replace Make with Gradle). Just listing this explicitly to highlight that it doesn't have to be all-or-nothing either.

As for gradle itself, I have to say that while I have used it superficially from time to time, I do have a bit of a (perhaps irrational) aversion to it and I would grumble a bit to have to dive into it. But again, this opinion is not a well-educated one so take it for what it is.


I did stumble upon a project a while back that I think could be interesting to check out for this, I'll see if I can find it again.

**Comment by ellenhp** [comment]
> The three main directions here would be:
> 
>     1. Keep current general Makefile+docker build combo but try to improve on it
> 
>     2. Separate the concerns and move the data processing part out of the build system to something different (probably something more made for the purpose)
> 
>     3. Replace the build system with something different

Seeing this spelled out makes me less eager to make a switch right now. The main downside of the current build system is that it relies excessively on docker images and bloats the disk usage, which is painful. Migrating the build system now might be a distraction though because Headway has pretty unique requirements and getting something that works well will take time away from other tasks. I'm currently pushing on #46, and moving towards a planet-scale demo of the system. A friend I trust has offered me a server with enough CPUs for this and 256GB of RAM on a gigabit connection, which should unblock a proper demo site. I'm really hoping that'll help the project attract more contributors who can help with frontend and productionization. That should probably be the priority for now because I think those are the main areas that are really lacking.

**Comment by 3nprob** [comment]
Finally found what I was thinking about: [Earthly](https://github.com/earthly/earthly). It seems like it could have a pretty nice migration path from the current setup.

**Comment by ellenhp** [comment]
Implemented by #81
