### ISSUE TITLE
Finish trip planner frontend

### ISSUE THREAD

**Issue by ellenhp** [headwaymaps/headway#63]
This was tracked in my head but it fell off my radar so it makes sense to track it explicitly I think. The trip planner frontend is the only mode that is completely unusable right now. Whereas the others are just missing ETAs and a decent nav experience, the trip planner is completely lacking because it doesn't display steps at all, only polylines representing each sub-trip.

**Comment by michaelkirk** [comment]
I think this was resolved in https://github.com/headwaymaps/headway/pull/200 (assuming by trip planner frontend you mean the OTP frontend). 

Let me know if you intended something else by this!
