### ISSUE TITLE
Building NewYork data ends up with an error

### ISSUE THREAD

**Issue by asitemade4u** [headwaymaps/headway#66]
Hi and thank you for this great project!

Unfortunately for me, I can't go through with the building of **NewYork base data**.

The `make NewYork` command begins failing at `16:53:00.408` with this message:

```log
ERROR (OTPMain.java:55) The provided transit date have no trips within the configured transit service period. See build config 'transitServiceStart' and 'transitServiceEnd': [2012-07-28, 2025-07-28]
16:53:00.415 INFO (OtpStartupInfo.java:47) OTP SHUTTING DOWN (version: 2.1.0, ser.ver.id: 2.1.0, commit: 0d24cc0a3f7ddddf1db87d805e09fd0ca70eb5b5, branch: master)
The command '/bin/sh -c java ${JAVA_MEM_ARGS} -jar /otp/otp-shaded.jar --build --save .' returned a non-zero code: 100
make: *** [Makefile:101: /mnt/cru/kuq/headway-main/data/NewYork.graph.obj] Error 100
```
As a result, the transportation data is not buit and the whole stack fails after Valhalla fails when launched.
Here is the (expected) error message in Valhalla's docker console:

```log
cp: cannot stat '/data_mount/NewYork.valhalla.tar': No such file or directory
```

Please help.
Thank you. Stephen

**Comment by ellenhp** [comment]
Thanks for the bug report! It looks like OpenTripPlanner is complaining about a transit agency not having any actual data. I bet I could detect that and filter it out in download_gtfs_feeds.py

**Comment by asitemade4u** [comment]
Thanks for the prompt response! Is there a way I can bypass Valhalla or is it too tightly knit into the fabric of the stack?
Also, is there a way I can use my own installation of Postgres -- as of now, the `docker-compose.yml` file does not mention Postgres?

**Comment by ellenhp** [comment]
Valhalla is the routing engine that powers headway, so no way to bypass it. Why do you need postgres? Headway doesn't use any databases.

**Comment by ellenhp** [comment]
Ahh nevermind, I had forgotten about nominatim. I'm not really sure if there's an easy way to use an external postgres with nominatim.

**Comment by asitemade4u** [comment]
Oh because I read the log and saw you were using Postgres in the 
building process.
But maybe that is only temporary...

**Comment by asitemade4u** [comment]
I guess there is but it is not a big deal.

**Comment by asitemade4u** [comment]
And BTW, I am building **Paris** and it also lifted an error, this time for lack of Java memory @17:43:43.851.
Here is the error message:
```log
17:43:16.938 INFO (GtfsModule.java:223) reading entities: org.onebusaway.gtfs.model.Vehicle
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.opentripplanner.model.PickDrop.values(PickDrop.java:3)
	at org.opentripplanner.model.PickDrop.fromGtfsCode(PickDrop.java:36)
	at org.opentripplanner.gtfs.mapping.StopTimeMapper.doMap(StopTimeMapper.java:70)
	at org.opentripplanner.gtfs.mapping.StopTimeMapper$$Lambda$205/0x0000000840369840.apply(Unknown Source)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at org.opentripplanner.gtfs.mapping.StopTimeMapper.map(StopTimeMapper.java:49)
	at org.opentripplanner.gtfs.mapping.StopTimeMapper$$Lambda$204/0x000000084036a440.apply(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1693)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.opentripplanner.util.MapUtils.mapToList(MapUtils.java:82)
	at org.opentripplanner.gtfs.mapping.StopTimeMapper.map(StopTimeMapper.java:44)
	at org.opentripplanner.gtfs.mapping.GTFSToOtpTransitServiceMapper.mapStopTripAndRouteDatantoBuilder(GTFSToOtpTransitServiceMapper.java:116)
	at org.opentripplanner.graph_builder.module.GtfsModule.buildGraph(GtfsModule.java:117)
	at org.opentripplanner.graph_builder.GraphBuilder.run(GraphBuilder.java:81)
	at org.opentripplanner.standalone.OTPMain.startOTPServer(OTPMain.java:136)
	at org.opentripplanner.standalone.OTPMain.main(OTPMain.java:52)
17:43:43.851 INFO (OtpStartupInfo.java:47) OTP SHUTTING DOWN (version: 2.1.0, ser.ver.id: 2.1.0, commit: 0d24cc0a3f7ddddf1db87d805e09fd0ca70eb5b5, branch: master)
The command '/bin/sh -c java ${JAVA_MEM_ARGS} -jar /otp/otp-shaded.jar --build --save .' returned a non-zero code: 1
make: *** [Makefile:101: /mnt/cru/par/headway-main/data/Paris.graph.obj] Error 1
```

**Comment by asitemade4u** [comment]
How do I increase the Java heap on the machine?

**Comment by ellenhp** [comment]
Should be right here.
https://github.com/headwaymaps/headway/blob/main/Makefile#L27

**Comment by asitemade4u** [comment]
I increased the heap to 20G at `JAVA_TOOL_OPTIONS := "-Xmx20G"` and it 
is still not enough, which seems weird to me.
Now trying with 24GB.

**Comment by ellenhp** [comment]
Did you increase the docker memory limit as well? If you're on a Mac you need to increase it at the system level too.

**Comment by asitemade4u** [comment]
Yup.
I tried with 30GB and it does the same.

So, I am stuck.

**Comment by ellenhp** [comment]
Did you increase it at the system level? I'm pretty sure Docker desktop
requires you to increase it in the GUI so unless you're on a linux machine
with a minimal docker installation you're going to need to do that.

**Comment by asitemade4u** [comment]
Forgot to tell I am using Linux / Rocky Linux 8 (= CentOS) on a Xeon 
server with 32GB memory.

**Comment by ellenhp** [comment]
Mkay, so that shouldn't be the problem. It's possible that it's OOMing because the Paris metro area is enormous. You might just need to wait until me or someone else tackles #32 if you're interested in using headway on huge cities. Sorry about that. I'll look into the crash in NYC when I get a chance, though, that shouldn't happen either way.

**Comment by asitemade4u** [comment]
Well, I am out of luck as I was born in Paris and now live in New York ;o)))

**Comment by asitemade4u** [comment]
FYI, I tried Philly and it worked. Yayyyy!

**Comment by ellenhp** [comment]
This should be fixed by #70. Testing NYC right now on my dev machine.

**Comment by asitemade4u** [comment]
Hi Ellen,
Thank you for the great work on NYC! I have tried installing the stack and it passed the error point I had mentioned.
However, I get yet another blocking error further down, this time at `ITAG=headway_build_fonts`, when installing fontnik.

Here is the trace in the console:
```log
Step 2/23 : RUN npm install fontnik
 ---> Running in a8d8a75e27b6
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/minimist failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-11T18_21_08_481Z-debug.log
The command '/bin/sh -c npm install fontnik' returned a non-zero code: 1
make: *** [Makefile:151: /mnt/cru/kuq/hwk/data/fonts.tar] Error 
```
As I understood it is an error while connecting to the NPM registry, I tried to connect manually using curl:
```bash
curl https://registry.npmjs.org/rc
```
And I got a correct response.

So I assume there is still an error there.
S.

**Comment by asitemade4u** [comment]
Also, the trace mentions a path for the logs which I was unable to find: `/root/.npm/_logs/2022-08-11T18_20_41_803Z-debug.log`
Please help me locate it so that I can send you the full error log.

**Comment by asitemade4u** [comment]
I also tried this, which might be more relevant:
```bash
curl https://registry.npmjs.org/rc/fontnik
```
And I got an error:
```log
{"code":"MethodNotAllowedError","message":"GET is not allowed"}
```
In hope that helped.

**Comment by ellenhp** [comment]
This appears to be related to network connectivity on your machine, or maybe with your docker configuration? Maybe try running that docker container interactively and test the network connectivity from within the container? But please open a new issue, I don't want to have this buried here in an unrelated bug.

**Comment by asitemade4u** [comment]
Will do ASAP.
