### ISSUE TITLE
Built Philadelphia successfully but tiles do not show

### ISSUE THREAD

**Issue by asitemade4u** [headwaymaps/headway#67]
So, I was able to build Philadelphia and to launch the docker stack successfully.
But when I access the server on port 8080:

- the interface shows,
- the routing engine works
- **but** the map (tiles) itself does not show.

I tried (on Debian) with Firefox and Brave browsers and the same.

**Comment by ellenhp** [comment]
Can you provide any additional information? Logs from the browser dev tools and docker containers, specifically.

**Comment by asitemade4u** [comment]
I checked all consoles from the docker containers and nothing seemed off 
-- no errors nor warnings.

**Comment by ellenhp** [comment]
Can you please provide them anyway, along with the full console logs of the dev tools inside of your browser. This is nowhere near enough information to diagnose the problem.

**Comment by asitemade4u** [comment]
Yes of course, I am on that now: I deleted all containers, pruned the 
system with `docker prune` and have launched `docker-compose up -d` 
again. Currently building.

As soon as I have a clean slate, will send results.

**Comment by ellenhp** [comment]
I should also mention that if you didn't follow the BUILD.md instructions correctly the bounding box will not be set correctly. So make sure you set up your `.env` from the example and specifically `HEADWAY_AREA` must be set to Philadelphia for this example.

**Comment by asitemade4u** [comment]
Yes of course, did so.

**Comment by asitemade4u** [comment]
Here are the errors reported in Firefox:

![Screenshot-20220728-193412](https://user-images.githubusercontent.com/11460106/181654306-60e896be-77ce-4242-b4e4-ac97ba167fba.png)

**Comment by ellenhp** [comment]
Did you set the public URL correctly? If it's a non-local installation you have to set the public URL.

**Comment by asitemade4u** [comment]
It is a local installation within 192.168.10.0/24
You mean in the `.env` file?

**Comment by ellenhp** [comment]
Yep. Just take the base URL in your browser and put it in there and it should come up just fine. Are you sure you're not accessing it via g11.qtpl.net:8080? because that's what firefox is saying in the logs.

**Comment by asitemade4u** [comment]
THAT WAS IT.
I changed the `HEADWAY_PUBLIC_URL` in the env`file and I can now see the 
tiles.

But the documentation is IMO a bit misleading as I am NOT publishing 
outside of my local network.

**Comment by ellenhp** [comment]
Glad it's working now! I'd love help with the docs if you want to submit a PR.

**Comment by asitemade4u** [comment]
Yup, will do.
