### ISSUE TITLE
[question] Possible to add a layer of information on top of the OSM tiles?

### ISSUE THREAD

**Issue by asitemade4u** [headwaymaps/headway#68]
Headway is GREAT and works fast.
I was wondering if it was possible to add one or several personal layers of POIs on top of the OSM tiles.
It would be useful, for example, to add GPS tracks, geolocate photos taken, etc.

**Comment by ellenhp** [comment]
This is not currently possible. It doesn't really fit with the design goals of the project as I originally envisioned it, but it would be cool to eventually get to the point where this was something that people could drop into Headway to extend it while benefiting from the build automation I've already done.

**Comment by asitemade4u** [comment]
Hi, sorry for responding so late as I was out of town.
You mean something like plugins? If so, yes, that is a great idea.
