### ISSUE TITLE
Network connectivity issue when pulling fontnik npm package

### ISSUE THREAD

**Issue by asitemade4u** [headwaymaps/headway#80]
Hi Ellen,
Thank you for the great work on NYC! I have tried installing the stack and it passed the error point I had mentioned.
However, I get yet another blocking error further down, this time at `ITAG=headway_build_fonts`, when installing fontnik.

Here is the trace in the console:
```log
Step 2/23 : RUN npm install fontnik
 ---> Running in a8d8a75e27b6
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/minimist failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-11T18_21_08_481Z-debug.log
The command '/bin/sh -c npm install fontnik' returned a non-zero code: 1
make: *** [Makefile:151: /mnt/cru/kuq/hwk/data/fonts.tar] Error 
```
As I understood it is an error while connecting to the NPM registry, I tried to connect manually using curl:
```bash
curl https://registry.npmjs.org/rc
```
And I got a correct response.

So I assume there is still an error there.
S.

_Originally posted by @asitemade4u in https://github.com/headwaymaps/headway/issues/66#issuecomment-1212344870_

**Comment by asitemade4u** [comment]
Also, the trace mentions a path for the logs which I was unable to find: /root/.npm/_logs/2022-08-11T18_20_41_803Z-debug.log
Please help me locate it so that I can send you the full error log.

**Comment by asitemade4u** [comment]
I also tried this, which might be more relevant:
```bash
curl https://registry.npmjs.org/rc/fontnik
```
And I got an error:
```log
{"code":"MethodNotAllowedError","message":"GET is not allowed"}
```
In hope that helped.

**Comment by ellenhp** [comment]
> Also, the trace mentions a path for the logs which I was unable to find: /root/.npm/_logs/2022-08-11T18_20_41_803Z-debug.log Please help me locate it so that I can send you the full error log.

This is going to be within the docker container. You're going to have to run it interactively to figure out what's going on.

**Comment by asitemade4u** [comment]
OK, but which container? You install several of them...

**Comment by ellenhp** [comment]
This one: https://github.com/headwaymaps/headway/blob/e0bae96eb3fa26e31866e2e4ba85673fbedb35d3/tileserver/assets/Dockerfile

If you `cd` into that directory and run `docker build` you should be able to reliably reproduce the issue, I'm guessing. If not then there's some weirdness happening.

Unrelated but fontnik has been very unreliable for a variety of reasons and it doesn't work at all on M1 Macs/amd64 machines so I'd like to replace it with something else if there's another way to generate those font files.

**Comment by asitemade4u** [comment]
Also, how can it be an error from within the container when the container is not running?
Here is what I do:

1. I do a `docker ps` > none of the containers displayed is by you
2. I `cd`  to the installation folder and `make NewYork`
3. I get the exact same error
4. I redo a `docker ps` > none of the containers displayed is by you

**Comment by asitemade4u** [comment]
Also, remember I am executing the install on a Linux server running CentOS8/Rocky Linux

**Comment by asitemade4u** [comment]
When I am trying the `docker build .` the build cannot find the `Dockerfile`

**Comment by asitemade4u** [comment]
OK, so I have indeed the same exact error when running `docker build .` from the `tileserver/assets` folder.

**Comment by asitemade4u** [comment]
And I can't figure out there might be a connectivity issue when the installation has been downloading stuff from the internet for more than 30mn before that happened ;o))

**Comment by ellenhp** [comment]
> Also, how can it be an error from within the container when the container is not running? Here is what I do:
> 
>     1. I do a `docker ps` > none of the containers displayed is by you
> 
>     2. I `cd`  to the installation folder and `make NewYork`
> 
>     3. I get the exact same error
> 
>     4. I redo a `docker ps` > none of the containers displayed is by you

Yeah sorry, I meant the container build environment, which I think is similar under the hood but I'm not sure.

Can you try following some of the troubleshooting in here: https://stackoverflow.com/questions/35515203/docker-npm-install-error-getaddrinfo-enotfound-registry-npmjs-org-registry-npmj

I don't think this is a bug in headway and I'm not really a docker expert so I'm not sure what to recommend.

**Comment by asitemade4u** [comment]
THANKS, this solution worked (I detail it in order to help others who might face it):

1. `cd` to `[install_folder]/tileset/assets`
2. Find all existing docker networks on the machine: `docker network ls` and chose one you know is working
3. execute `docker build . --network=[network_ID_chosen]`
4. It should go through
5. Then go back to the `[install_folder` and resume installation using `make [the_city]`

**Comment by ellenhp** [comment]
It sounds like the default docker network might not be working on you server, which could mess with other things so might be worth looking into separately. Feel free to open another issue if you have anything else, or join the headway matrix channel if you plan on running an instance. I don't have many users right now so it would be cool to get feedback from people who do run instances :)

https://matrix.to/#/#headway:matrix.org

**Comment by asitemade4u** [comment]
Well, I am not sure: there are already 31 stacks that work perfectly on the server...
But good ndews: NewYork went through!
