### ISSUE TITLE
The HEADWAY_FORCE_BBOX environment variable does not seem to respond

### ISSUE THREAD

**Issue by asitemade4u** [headwaymaps/headway#86]
So:

1. I have deployed the `NewYork` stack
2. using [BBox Finder](http://bboxfinder.com), I have defined a BBox for the map
3. I have added this entry in the `.env` file: `HEADWAY_FORCE_BBOX="-74.051971,40.622813,-73.893013,40.751418"`
4. But nothing special happens, except that the error message displayed when there is no BBox defined does not show any longer.

**Comment by ellenhp** [comment]
Which error messages? I'm also going to need the full output of `docker-compose logs`

**Comment by ellenhp** [comment]
Oh wait nevermind, your bbox is formatted wrong. It's `lng lat lng lat` space-delimited. Should be documented in the build file. Feel free to reopen if you have more issues with this.
