### ISSUE TITLE
HEADWAY_FORCE_BBOX

### ISSUE THREAD

**Issue by asitemade4u** [headwaymaps/headway#87]
I tried `HEADWAY_FORCE_BBOX="-74.051971 40.622813 -73.893013 40.751418"` and it still does not work

**Comment by ellenhp** [comment]
I can't do anything with this bug report. Please give me more information....

**Comment by asitemade4u** [comment]
I reopened the #86 closed bug, as you had requested

**Comment by ellenhp** [comment]
I'm going to make an issue template, but in general bug reports need at least the following to be reproduced and fixed:

1. What you did
2. What you expected to happen
3. What happened
4. Logs

For 4, specifically in the case of headway that's everything in the browser developer console when you load the app, and everything in `docker-compose logs` when you bring up the stack.

For build errors, I'll need the full output of `make CityName`
